stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ssxs/ssxs-centos7:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry-vpc.cn-shenzhen.aliyuncs.com
timeout: 60
notification: {}
