stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ssxs-centos7:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.cn-shenzhen.aliyuncs.com/ssxs-docker/ssxs-repo
timeout: 60
notification: {}
